env: development
port: :8081
grpc_port: :8082
mysql:
  dbhost: localhost:3306
  dbname: kodinggo
  dbusername: root
  dbpassword: 
jwt:
  signing_key: bq6M68YCXnv2iltpH3h6dz51xn2Uv3dh
  exp: 24h
comment_service:
  grpc_port: :8083